"""backend/core/compose.py

Builds and merges Docker Compose fragments.

Each deployed service has its own fragment stored at:
  {data_dir}/compose/{key}.yaml

The final docker-compose.yml is produced by merging all active fragments.
This means adding or removing a service is surgical — no regenerating
the whole stack from scratch.

The Traefik fragment is special: it's generated by the platform wizard
and always included. All other fragments are generated from manifests.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from backend.core.config import config
from backend.core.logging import get_logger

# Docker compose subprocess command helpers live in a sibling module to keep this file under the
# production_code cap (#1302). Imported back + re-exported (redundant-alias idiom) so existing
# callers — the infra providers' `from backend.core.compose import compose_up` etc. — keep resolving.
from backend.core.compose_cli import (
    compose_down as compose_down,
    compose_pull as compose_pull,
    compose_pull_stream as compose_pull_stream,
    compose_up as compose_up,
)

log = get_logger(__name__)

STACK_NETWORK = "slop"


# ---------------------------------------------------------------------------
# Fragment builders
# ---------------------------------------------------------------------------


# Environment variables required by each DNS provider for ACME DNS-01 challenge.
# Traefik reads these from its own container environment.
_PROVIDER_ENV_VARS: dict[str, list[str]] = {
    "cloudflare": ["CF_DNS_API_TOKEN"],
    "route53": ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION", "AWS_HOSTED_ZONE_ID"],
    "namecheap": ["NAMECHEAP_API_USER", "NAMECHEAP_API_KEY"],
    "porkbun": ["PORKBUN_API_KEY", "PORKBUN_SECRET_API_KEY"],
    "digitalocean": ["DO_AUTH_TOKEN"],
    "gandi": ["GANDI_PERSONAL_ACCESS_TOKEN"],
    "hetzner": ["HETZNER_API_KEY"],
    "linode": ["LINODE_TOKEN"],
    "ovh": ["OVH_ENDPOINT", "OVH_APPLICATION_KEY", "OVH_APPLICATION_SECRET", "OVH_CONSUMER_KEY"],
    "godaddy": ["GODADDY_API_KEY", "GODADDY_API_SECRET"],
    "duckdns": ["DUCKDNS_TOKEN"],
    "desec": ["DESEC_TOKEN"],
    "njalla": ["NJALLA_TOKEN"],
    "inwx": ["INWX_USERNAME", "INWX_PASSWORD"],
    "infomaniak": ["INFOMANIAK_ACCESS_TOKEN"],
    # Additional providers
    "azure": [
        "AZURE_CLIENT_ID",
        "AZURE_CLIENT_SECRET",
        "AZURE_SUBSCRIPTION_ID",
        "AZURE_RESOURCE_GROUP",
    ],
    "google": ["GCE_PROJECT", "GCE_SERVICE_ACCOUNT_FILE"],
    "vultr": ["VULTR_API_KEY"],
    "bunny": ["BUNNY_API_KEY"],
    "dnspod": ["DNSPOD_API_KEY", "DNSPOD_SECRET_ID"],
}


def build_traefik_fragment(
    domain: str,
    config_root: str,
    network_name: str = STACK_NETWORK,
    cert_resolver: str = "letsencrypt",
    dns_provider: str = "cloudflare",
    env_overrides: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Generate the Traefik service compose fragment.

    Passes all environment variables required by the configured DNS provider
    so Traefik can complete the DNS-01 ACME challenge.
    Non-CF providers (Route53, Namecheap, Porkbun, etc.) previously received
    no env vars and cert issuance would silently fail.
    """
    traefik_config_path = f"{config_root}/traefik"
    acme_path = f"{traefik_config_path}/acme.json"
    # ZeroSSL uses a separate storage file — must be mounted so it persists
    acme_zerossl_path = f"{traefik_config_path}/acme-zerossl.json"

    # Build env dict: bake resolved values when provided so the fragment works
    # without shell interpolation (e.g. manual docker compose runs).
    provider_vars = _PROVIDER_ENV_VARS.get(dns_provider, [])
    _ov = env_overrides or {}
    env = {var: _ov.get(var) or f"${{{var}}}" for var in provider_vars}
    # Traefik v3 does not negotiate the Docker API version via /_ping when
    # connecting over TCP; it defaults to the SDK minimum (1.24) which Docker
    # 29+ rejects (min 1.40).  Setting this explicitly skips negotiation.
    env["DOCKER_API_VERSION"] = "1.47"

    # Read image tag and dashboard port from settings
    try:
        from backend.core.state import StateDB as _SDB

        with _SDB() as _db:
            _tag = _db.get_setting("traefik_image_tag") or "v3.2"
            _port = int(_db.get_setting("traefik_dashboard_port") or "8081")
    except Exception:
        _tag, _port = "v3.2", 8081

    return {
        "image": f"traefik:{_tag}",
        "container_name": "traefik",
        "restart": "unless-stopped",
        "networks": [network_name],
        "ports": [
            "80:80",
            "443:443",
            f"127.0.0.1:{_port}:8080",  # dashboard — localhost only until auth deployed
        ],
        "volumes": [
            f"{traefik_config_path}/traefik.yml:/traefik.yml:ro",
            f"{traefik_config_path}/dynamic:/config/traefik/dynamic",
            f"{acme_path}:/acme.json",
            f"{acme_zerossl_path}:/acme-zerossl.json",
            f"{traefik_config_path}/acme-buypass.json:/acme-buypass.json",
            f"{traefik_config_path}/acme-staging.json:/acme-staging.json",
            "/var/run/docker.sock:/var/run/docker.sock:ro",
        ],
        "environment": env,
        "labels": [
            "traefik.enable=true",
            f"traefik.http.routers.traefik.rule=Host(`traefik.{domain}`)",
            "traefik.http.routers.traefik.entrypoints=websecure",
            "traefik.http.routers.traefik.tls=true",
            f"traefik.http.routers.traefik.tls.certresolver={cert_resolver}",
            "traefik.http.routers.traefik.service=api@internal",
            # traefik-auth middleware added by wizard when auth infra slot is deployed
        ],
    }


# ACME cert resolver definitions. Adding a new CA = one new dict entry here.
# "when": "selected" = only emitted when cert_resolver matches the name.
# "when": "always"   = always emitted (ZeroSSL as hot-standby) unless opted out.
_ACME_RESOLVERS: list[dict[str, Any]] = [
    {
        "name": "letsencrypt",
        "ca_server": None,  # omitted → Traefik uses the LE production default
        "storage": "/acme.json",
        "delay": True,
        "eab": False,
        "when": "selected",
    },
    {
        "name": "zerossl",
        "ca_server": "https://acme.zerossl.com/v2/DV90",
        "storage": "/acme-zerossl.json",
        "delay": False,
        "eab": True,  # supports optional EAB credentials
        "when": "always",  # hot-standby; opt out via include_zerossl=False
    },
    {
        "name": "buypass",
        "ca_server": "https://api.buypass.com/acme/directory",
        "storage": "/acme-buypass.json",
        "delay": False,
        "eab": False,
        "when": "selected",
    },
    {
        "name": "staging",
        "ca_server": "https://acme-staging-v02.api.letsencrypt.org/directory",
        "storage": "/acme-staging.json",
        "delay": True,
        "eab": False,
        "when": "selected",
    },
]


def _render_resolver(
    r: dict[str, Any],
    email: str,
    dns_provider: str,
    eab_kid: str,
    eab_hmac: str,
) -> str:
    """Render one certificatesResolvers YAML block from a resolver definition."""
    lines = [f"\n  {r['name']}:", "    acme:", f"      email: {email}"]
    if r["ca_server"]:
        lines.append(f"      caServer: {r['ca_server']}")
    lines.append(f"      storage: {r['storage']}")
    if r["eab"] and eab_kid and eab_hmac:
        lines += ["      eab:", f"        kid: {eab_kid}", f"        hmacEncoded: {eab_hmac}"]
    lines += [
        "      dnsChallenge:",
        f"        provider: {dns_provider}",
        "        resolvers:",
        '          - "1.1.1.1:53"',
        '          - "8.8.8.8:53"',
    ]
    if r["delay"]:
        lines.append("        delayBeforeCheck: 30s")
    return "\n".join(lines) + "\n"


def build_traefik_yaml(
    domain: str,
    cert_resolver: str = "letsencrypt",
    acme_email: str = "",
    dns_provider: str = "cloudflare",
    include_zerossl: bool = True,
    eab_kid: str = "",
    eab_hmac: str = "",
    socket_proxy: bool = False,
) -> str:
    """Generate the traefik.yml static config content.

    Uses DNS-01 challenge exclusively — supports wildcard certs and requires
    no open ports. Supported dns_provider values (via Traefik/lego): cloudflare,
    route53, namecheap, porkbun, digitalocean, gandi, duckdns, hetzner, linode,
    ovh, godaddy, njalla, google, azure, desec, infomaniak, and 80+ more.
    Full list: https://doc.traefik.io/traefik/https/acme/#providers
    """
    email = acme_email or f"admin@{domain}"
    # Use socket proxy endpoint for least-privilege Docker access when deployed.
    _docker_endpoint = (
        "tcp://docker-socket-proxy:2375" if socket_proxy else "unix:///var/run/docker.sock"
    )

    resolver_blocks = ""
    for r in _ACME_RESOLVERS:
        if r["when"] == "selected" and cert_resolver != r["name"]:
            continue
        if r["when"] == "always" and not (include_zerossl or cert_resolver == r["name"]):
            continue
        resolver_blocks += _render_resolver(r, email, dns_provider, eab_kid, eab_hmac)

    return f"""\
# Traefik static configuration — managed by SLOP
# Do not edit manually; re-run the platform wizard to regenerate.
# DNS-01 challenge: no open ports needed for cert issuance.
# Wildcard cert (*.{domain}) covers every app subdomain automatically.

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        # Wildcard cert applied globally — every subdomain gets HTTPS
        # automatically without per-app certificate configuration.
        certResolver: {cert_resolver}
        domains:
          - main: "*.{domain}"
            sans:
              - "{domain}"

providers:
  docker:
    endpoint: "{_docker_endpoint}"
    exposedByDefault: false
    network: {STACK_NETWORK}
  file:
    directory: /config/traefik/dynamic
    watch: true

certificatesResolvers:{resolver_blocks}"""


# System-reserved host ports that Traefik or SLOP already own —
# apps whose internal port matches one of these can't bind a host port,
# they're reachable via Traefik hostname routing only.
#   80/443 → Traefik HTTP/HTTPS,  8080 → SLOP UI,  8081 → Traefik dashboard
_SYSTEM_PORTS: frozenset[int] = frozenset({80, 443, 8080, 8081})

# Optional fragment keys whose values must be `list()`-copied before
# being set on the fragment dict (snapshot semantics — see
# build_service_fragment).
_FRAGMENT_LIST_KEYS: frozenset[str] = frozenset({"cap_add", "security_opt", "devices"})


def _frag_env(
    linuxserver: bool,
    puid: int,
    pgid: int,
    timezone: str,
    static_env: dict[str, str] | None,
    env_overrides: dict[str, str] | None,
) -> dict[str, str]:
    """Assemble the `environment:` block.
    Order: linuxserver PUID/PGID/TZ → static_env → env_overrides (escaped).
    Override order matches the original (overrides win)."""
    env: dict[str, str] = {}
    if linuxserver:
        env["PUID"] = str(puid)
        env["PGID"] = str(pgid)
        env["TZ"] = timezone
    if static_env:
        env.update(static_env)
    if env_overrides:
        env.update({k: _esc(str(v)) for k, v in env_overrides.items()})
    return env


def _frag_volumes(
    config_path: str,
    config_container: str,
    media_root: str | None,
    media_container: str,
    extra_volumes: list[dict[str, Any]] | None,
) -> list[str]:
    """Assemble the `volumes:` block. Config always present, mounted at the
    manifest's container config path (`config_container`, default `/config`);
    media added at `media_container` (default `/data`) when media_root is set;
    extra_volumes appended raw. The container paths MUST come from the manifest
    (`config_volume`/`media_volume`) — most non-linuxserver images read config
    from an image-specific path (e.g. glance /app/config, adguard
    /opt/adguardhome/conf), so a hardcoded /config silently mis-mounts them."""
    volumes = [f"{config_path}:{config_container}"]
    if media_root:
        volumes.append(f"{media_root}:{media_container}")
    if extra_volumes:
        for vol in extra_volumes:
            ro = ":ro" if vol.get("readonly") else ""
            volumes.append(f"{vol['host']}:{vol['container']}{ro}")
    return volumes


def _frag_ports(web_port: int | None, host_port: int | None) -> list[str]:
    """Assemble the `ports:` block. Empty list when either port is unset or
    when web_port is a system-reserved port.

    Defense-in-depth: even though _compute_host_port (install path) also
    guards against system ports, _frag_ports applies the guard independently
    so that any caller that bypasses the install path (direct fragment build,
    tests, future code paths) cannot accidentally bind a system port.

    Traefik's own 80/443 bindings are NOT affected — build_traefik_fragment
    uses hardcoded port strings and does not go through _frag_ports."""
    if web_port and host_port and web_port not in _SYSTEM_PORTS:
        return [f"{host_port}:{web_port}"]
    return []


def _frag_healthcheck(web_port: int | None, start_grace_s: int) -> dict[str, Any] | None:
    """Docker-level healthcheck with `start_period` so Docker doesn't
    restart the container during its boot window. None when no web
    port is exposed or no start grace is configured — the absence of
    a healthcheck section is the canonical 'no Docker-level check'."""
    grace = start_grace_s or 0
    if not (web_port and grace > 0):
        return None
    return {
        "test": [
            "CMD-SHELL",
            f"wget -qO- http://localhost:{web_port}/ > /dev/null 2>&1 || exit 1",
        ],
        "interval": "30s",
        "timeout": "10s",
        "retries": 3,
        "start_period": f"{grace}s",
    }


def build_service_fragment(
    manifest_key: str,
    display_name: str,
    image: str,
    image_tag: str,
    web_port: int | None,
    host_port: int | None,
    config_path: str,
    media_root: str | None,
    domain: str,
    config_volume: str = "/config",
    media_volume: str = "/data",
    network_name: str = STACK_NETWORK,
    puid: int = 1000,
    pgid: int = 1000,
    timezone: str = "UTC",
    linuxserver: bool = True,
    env_overrides: dict[str, str] | None = None,
    static_env: dict[str, str] | None = None,
    cert_resolver: str = "letsencrypt",
    lan_subnet: str | None = None,
    tinyauth_enabled: bool = False,
    extra_volumes: list[dict[str, Any]] | None = None,
    capabilities: list[str] | None = None,
    security_opt: list[str] | None = None,
    devices: list[str] | None = None,
    shm_size: str | None = None,
    service_type: str = "management",
    start_grace_s: int = 0,
) -> dict[str, Any]:
    """Build a service compose fragment from manifest data.

    Step 2.7.e: extracts environment / volumes / ports / healthcheck
    phases into helpers (`_frag_env`, `_frag_volumes`, `_frag_ports`,
    `_frag_healthcheck`) and assembles the optional fragment keys via
    a (key, value) table loop — drops complexity from 17 to ≤ 4.
    """
    fragment: dict[str, Any] = {
        "image": f"{image}:{image_tag}",
        "container_name": manifest_key,
        "restart": "unless-stopped",
        "networks": [network_name],
    }

    # Management labels always present (ADR 0017 §D): purge/clean enumeration depends on them.
    _labels: list[str] = [
        "slop.managed=true",
        f"slop.app-key={manifest_key}",
    ]
    _labels.extend(
        _route_labels(
            key=manifest_key,
            domain=domain,
            web_port=web_port,
            cert_resolver=cert_resolver,
            lan_subnet=lan_subnet,
            tinyauth_enabled=tinyauth_enabled,
        )
    )
    fragment["labels"] = _labels

    optional: list[tuple[str, Any]] = [
        ("environment", _frag_env(linuxserver, puid, pgid, timezone, static_env, env_overrides)),
        (
            "volumes",
            _frag_volumes(config_path, config_volume, media_root, media_volume, extra_volumes),
        ),
        ("ports", _frag_ports(web_port, host_port)),
        ("cap_add", capabilities),
        ("security_opt", security_opt),
        ("devices", devices),
        ("shm_size", shm_size),
        ("healthcheck", _frag_healthcheck(web_port, start_grace_s)),
    ]
    for key, value in optional:
        if value:
            fragment[key] = list(value) if key in _FRAGMENT_LIST_KEYS else value
    return fragment


def _route_labels(
    key: str,
    domain: str,
    web_port: int | None,
    cert_resolver: str,
    lan_subnet: str | None,
    tinyauth_enabled: bool,
) -> list[str]:
    """Per-app reverse-proxy route labels, emitted BY-REFERENCE through the active
    reverse_proxy slot provider (#990 P2).

    The provider (Traefik today) is the SOLE raw ``traefik.http.*`` per-app emitter —
    this module no longer hardcodes those strings; it dispatches to
    ``provider.emit_route_labels``. The lazy import breaks the compose↔infra module
    cycle (the provider imports compose's deploy helpers at module load); the emission
    is pure (no I/O) so fragment building stays side-effect-free.

    reverse_proxy is one-active. The active provider key is resolved from the infra_slots
    DB row (#1272 / #990 P3) — no longer hardcoded to ``traefik`` — degrading to ``traefik``
    (the always-registered built-in floor) when the DB / slot row / configured key is
    unavailable. This dispatcher is NOT pure (it reads the DB via ``_active_reverse_proxy_key``);
    the per-app label STRINGS are still emitted purely by ``provider.emit_route_labels``. The
    DB read is confined here so fragment building works without a slot row.
    """
    from backend.infra.registry import get_provider

    key_ = _active_reverse_proxy_key()
    try:
        provider = get_provider("reverse_proxy", key_)
    except KeyError:
        # Configured provider not registered (e.g. a removed plugin) — degrade to Traefik
        # rather than fail fragment building. Traefik itself is the built-in floor and is
        # always registered (_ensure_providers_registered); a missing Traefik is a fatal
        # misconfiguration that SHOULD surface loudly here, exactly as the pre-#1272 code
        # (which called this same unconditional get_provider) would have.
        provider = get_provider("reverse_proxy", "traefik")
    return provider.emit_route_labels(
        key, domain, web_port, cert_resolver, lan_subnet, tinyauth_enabled
    )


def _active_reverse_proxy_key() -> str:
    """Resolve the configured active ``reverse_proxy`` provider key from the infra_slots DB.

    Falls back to ``"traefik"`` (the sole provider today) on ANY failure: no DB, used
    outside a context, missing/unseeded slot row, or an empty provider column. This keeps
    ``build_service_fragment`` working without a slot row (mirrors the StateDB-read+fallback
    pattern used for the Traefik image tag above). Validation that the key is *registered*
    is done by the caller (it has the registry import), so a stale DB key still degrades
    gracefully to Traefik.
    """
    try:
        from backend.core.state import StateDB as _SDB

        with _SDB() as _db:
            key_ = _db.get_slot("reverse_proxy").provider
    except Exception:
        # Deliberately broad: this is a must-never-break-fragment-building path with a safe
        # default, so a DB-unavailable env (no DB, outside-context, unseeded slot, locked
        # file) degrades rather than aborts the install. Mirrors the identical bare-except +
        # default in build_traefik_fragment above (the local idiom for DB-optional reads).
        return "traefik"
    return key_ or "traefik"


def _esc(value: str) -> str:
    """Escape $ in user-supplied values so Docker Compose doesn't interpolate them."""
    if not value:
        return value
    if value.startswith("${") and value.endswith("}"):
        return value  # intentional placeholder — leave as-is
    return value.replace("$", "$$")


# ---------------------------------------------------------------------------
# Fragment persistence
# ---------------------------------------------------------------------------

_MANAGED_LABEL = "slop.managed=true"


def _apply_managed_label(service_dict: dict[str, Any]) -> dict[str, Any]:
    """Ensure a service dict carries the slop.managed=true label.

    This is the single enforcement point (ADR 0017 §D): every service written
    via write_fragment gets the label regardless of which builder produced it.
    Handles both list[str] labels (``["key=val", ...]``) and dict labels
    (``{"key": "val", ...}``); normalises to list form to match the rest of the
    codebase.  Idempotent — calling twice is safe.
    """
    existing = service_dict.get("labels")
    if existing is None:
        service_dict["labels"] = [_MANAGED_LABEL]
    elif isinstance(existing, dict):
        # Convert dict shape to list form, then insert if absent.
        label_list = [f"{k}={v}" for k, v in existing.items()]
        if _MANAGED_LABEL not in label_list:
            label_list.insert(0, _MANAGED_LABEL)
        service_dict["labels"] = label_list
    else:
        # list[str] shape — normalise in-place equivalent
        labels: list[str] = list(existing)
        if _MANAGED_LABEL not in labels:
            labels.insert(0, _MANAGED_LABEL)
        service_dict["labels"] = labels
    return service_dict


def write_fragment(
    key: str,
    service_def: dict[str, Any],
    network_name: str = STACK_NETWORK,
    named_volumes: list[str] | None = None,
) -> Path:
    """Write a service compose fragment to disk.

    Includes a top-level networks: external declaration so each fragment can
    be run standalone with docker compose -f key.yaml up -d without Compose
    complaining that the network is undefined.

    ``named_volumes`` — Docker named volumes the service references (e.g. a
    managed DB's ``<svc>_data``). They are declared in a top-level ``volumes:``
    block so compose can resolve them when the fragment runs standalone; without
    the declaration compose errors on the undefined volume (#1203).

    Every service written here is normalised via _apply_managed_label so that
    slop.managed=true is always present (ADR 0017 §D), regardless of which
    builder produced the fragment.
    """
    fragment_dir = config.compose_dir
    fragment_dir.mkdir(parents=True, exist_ok=True)

    path = fragment_dir / f"{key}.yaml"
    content: dict[str, Any] = {
        "services": {key: _apply_managed_label(service_def)},
        "networks": {network_name: {"external": True}},
    }
    if named_volumes:
        content["volumes"] = {vol: {} for vol in named_volumes}
    path.write_text(yaml.dump(content, default_flow_style=False, sort_keys=False))
    log.debug("Wrote compose fragment: %s", path)
    return path


def remove_fragment(key: str) -> None:
    """Remove a service compose fragment."""
    path = config.compose_dir / f"{key}.yaml"
    if path.exists():
        path.unlink()
        log.info("Removed compose fragment: %s", path)


def merge_fragments(network_name: str = STACK_NETWORK) -> str:
    """Merge all active fragments into a single docker-compose.yml string."""
    fragment_dir = config.compose_dir
    if not fragment_dir.exists():
        return ""

    merged: dict[str, Any] = {
        "networks": {
            network_name: {"external": True},
        },
        "services": {},
    }

    for frag_path in sorted(fragment_dir.glob("*.yaml")):
        try:
            frag = yaml.safe_load(frag_path.read_text()) or {}
            services = frag.get("services", {})
            merged["services"].update(services)
        except yaml.YAMLError as e:
            log.warning("Skipping malformed fragment %s: %s", frag_path.name, e)

    return yaml.dump(merged, default_flow_style=False, sort_keys=False)


def write_compose_file(output_path: Path, network_name: str = STACK_NETWORK) -> Path:
    """Write the merged docker-compose.yml to disk."""
    content = merge_fragments(network_name)
    output_path.write_text(content)
    log.info("Wrote docker-compose.yml: %s", output_path)
    return output_path


_SOCKET_PROXY_HAPROXY_TEMPLATE = (Path(__file__).parent / "templates" / "haproxy.cfg").read_text()


def build_socket_proxy_fragment(
    network_name: str = STACK_NETWORK,
    config_root: str = "",
) -> dict[str, Any]:
    """Build compose fragment for Tecnativa docker-socket-proxy.

    The proxy sits between Traefik and the Docker socket, restricting
    Traefik to read-only API calls only. This prevents Traefik from
    executing arbitrary Docker operations even if compromised.

    Traefik is configured to use this proxy instead of the raw socket.
    """
    volumes = ["/var/run/docker.sock:/var/run/docker.sock:ro"]
    if config_root:
        tmpl = f"{config_root}/socket-proxy/haproxy.cfg.template"
        volumes.append(f"{tmpl}:/usr/local/etc/haproxy/haproxy.cfg.template:ro")

    return {
        "image": "tecnativa/docker-socket-proxy:v0.4.2",  # last-verified: 2026-06-07
        "container_name": "docker-socket-proxy",
        "networks": [network_name],
        "environment": {
            # Allowlist: only what Traefik needs
            "CONTAINERS": "1",
            "SERVICES": "1",
            "NETWORKS": "1",
            "TASKS": "1",
            "EVENTS": "1",
            "INFO": "1",
            # Required for Traefik's Docker API version negotiation.
            # Without PING=1, the proxy blocks /_ping, negotiation fails, and
            # Traefik's client gets stuck at its SDK minimum (v1.24) which
            # Docker 29+ rejects (min 1.40).
            "PING": "1",
            # Traefik v3 calls /version to retrieve server info on startup.
            # Without VERSION=1 the proxy returns 403 and the provider fails.
            "VERSION": "1",
            # Deny write operations
            "VOLUMES": "0",
            "IMAGES": "0",
            "AUTH": "0",
            "POST": "0",
            "DELETE": "0",
        },
        "volumes": volumes,
        "expose": ["2375"],
        "restart": "unless-stopped",
        "security_opt": ["no-new-privileges:true"],
    }
