"""backend/platform/storage.py

External storage source manager.

Handles two categories:

  LAN NAS (nfs / smb)
    → Generates systemd .mount unit files installed on the host.
    → Docker sees them as ordinary local paths (bind mounts).
    → No container needed — kernel handles the connection.

  Cloud / remote (rclone)
    → Generates rclone.conf remote definitions.
    → Deploys an rclone container instance per source.
    → FUSE mount shared via rshared propagation.

  Local paths (local)
    → Already mounted on the host. SLOP just records the path.

Multiple sources can be defined. The primary source is used as media_root.
If MergerFS is present on the host, SLOP can optionally unify all
NAS sources into a single merged mount.
"""

from __future__ import annotations

import json
import os
import re as _re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from backend.core.logging import get_logger
from backend.core.state import StateDB

log = get_logger(__name__)


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass
class StorageSource:
    id: int | None
    name: str
    source_type: str  # nfs | smb | rclone | local
    remote_host: str | None  # IP or hostname
    remote_path: str | None  # NFS export or SMB share name
    mount_point: str  # /mnt/nas01
    credentials_key: str | None
    options: dict[str, Any]  # parsed from JSON
    is_primary: bool
    status: str  # active | inactive | error | mounting
    error_message: str | None


@dataclass
class MountConfig:
    """Generated configuration for a storage source."""

    source: StorageSource
    # Systemd .mount unit (nfs/smb)
    systemd_unit: str | None = None
    systemd_unit_name: str | None = None
    # fstab entry (alternative to systemd)
    fstab_entry: str | None = None
    # rclone remote config (rclone sources)
    rclone_remote_name: str | None = None
    rclone_conf_block: str | None = None
    # Install instructions (plain language)
    install_steps: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Systemd mount unit generator (NFS / SMB)
# ---------------------------------------------------------------------------


def _systemd_unit_name(mount_point: str) -> str:
    """Convert a mount path to a systemd unit name.

    /mnt/nas01 → mnt-nas01.mount
    /mnt/cloud/backblaze → mnt-cloud-backblaze.mount
    """
    stripped = mount_point.lstrip("/")
    escaped = stripped.replace("-", "\\x2d").replace("/", "-")
    return f"{escaped}.mount"


def _sanitize_path_component(value: str, field_name: str) -> str:
    """Sanitize a path/host component used in shell commands or unit files.

    Rejects values containing shell metacharacters to prevent command injection
    in systemd unit files and mount commands.
    """
    # Allow: alphanumeric, dots, hyphens, underscores, forward slashes, colons (for IPv6)
    if _re.search(r"[^a-zA-Z0-9./_:\-]", value):
        raise ValueError(
            f"Invalid characters in {field_name} '{value}'. "
            f"Only alphanumeric, dots, hyphens, underscores, slashes, and colons are allowed."
        )
    return value


def generate_nfs_unit(source: StorageSource) -> MountConfig:
    """Generate a systemd .mount unit for an NFS share."""
    opts = source.options or {}
    nfs_version = opts.get("nfs_version", "4.1")
    extra_opts = opts.get("extra_options", "")
    mount_options = f"nfsvers={nfs_version},_netdev,auto,nofail,x-systemd.automount"
    if extra_opts:
        mount_options += f",{extra_opts}"

    unit_name = _systemd_unit_name(source.mount_point)
    host = _sanitize_path_component(source.remote_host or "", "remote_host")
    path = _sanitize_path_component(source.remote_path or "", "remote_path")
    what = f"{host}:{path}"

    unit_content = f"""\
# Generated by SLOP — do not edit manually
# Storage source: {source.name}
# Regenerate: SLOP → Storage → {source.name} → Regenerate Config

[Unit]
Description=SLOP NFS Mount — {source.name}
Documentation=https://github.com/Nnyan/SLOP
Before=docker.service
After=network-online.target
Wants=network-online.target

[Mount]
What={what}
Where={source.mount_point}
Type=nfs
Options={mount_options}
TimeoutSec=30

[Install]
WantedBy=multi-user.target
"""

    install_steps = [
        "sudo apt-get install -y nfs-common",
        f"sudo mkdir -p {source.mount_point}",
        f"sudo cp /etc/slop/mounts/{unit_name} /etc/systemd/system/",
        "sudo systemctl daemon-reload",
        f"sudo systemctl enable --now {unit_name}",
        f"systemctl status {unit_name}",
    ]

    fstab = f"{what}  {source.mount_point}  nfs  {mount_options}  0 0"

    return MountConfig(
        source=source,
        systemd_unit=unit_content,
        systemd_unit_name=unit_name,
        fstab_entry=fstab,
        install_steps=install_steps,
    )


def generate_smb_unit(source: StorageSource) -> MountConfig:
    """Generate a systemd .mount unit for an SMB/CIFS share."""
    opts = source.options or {}
    smb_version = opts.get("smb_version", "3.0")
    uid = opts.get("uid", 1000)
    gid = opts.get("gid", 1000)
    file_mode = opts.get("file_mode", "0664")
    dir_mode = opts.get("dir_mode", "0775")

    # Credentials file path — credentials stored in /etc/slop/secrets/
    cred_path = f"/etc/slop/secrets/{source.name.replace(' ', '_').lower()}.cred"

    mount_options = (
        f"credentials={cred_path},vers={smb_version},"
        f"uid={uid},gid={gid},file_mode={file_mode},dir_mode={dir_mode},"
        f"_netdev,auto,nofail,x-systemd.automount"
    )
    extra = opts.get("extra_options", "")
    if extra:
        mount_options += f",{extra}"

    unit_name = _systemd_unit_name(source.mount_point)
    host = _sanitize_path_component(source.remote_host or "", "remote_host")
    path = _sanitize_path_component(source.remote_path or "", "remote_path")
    what = f"//{host}/{path}"

    unit_content = f"""\
# Generated by SLOP — do not edit manually
# Storage source: {source.name}

[Unit]
Description=SLOP SMB Mount — {source.name}
Documentation=https://github.com/Nnyan/SLOP
Before=docker.service
After=network-online.target
Wants=network-online.target

[Mount]
What={what}
Where={source.mount_point}
Type=cifs
Options={mount_options}
TimeoutSec=30

[Install]
WantedBy=multi-user.target
"""

    install_steps = [
        "sudo apt-get install -y cifs-utils",
        f"sudo mkdir -p {source.mount_point}",
        "# Create credentials file (never store passwords in fstab or unit files):",
        "sudo mkdir -p /etc/slop/secrets",
        f"sudo bash -c 'echo -e \"username=YOUR_USERNAME\\npassword=YOUR_PASSWORD\\ndomain=WORKGROUP\" > {cred_path}'",
        f"sudo chmod 600 {cred_path}",
        f"sudo cp /etc/slop/mounts/{unit_name} /etc/systemd/system/",
        "sudo systemctl daemon-reload",
        f"sudo systemctl enable --now {unit_name}",
        f"systemctl status {unit_name}",
    ]

    fstab = f"{what}  {source.mount_point}  cifs  {mount_options}  0 0"

    return MountConfig(
        source=source,
        systemd_unit=unit_content,
        systemd_unit_name=unit_name,
        fstab_entry=fstab,
        install_steps=install_steps,
    )


# ---------------------------------------------------------------------------
# rclone remote generator (cloud sources)
# ---------------------------------------------------------------------------


def generate_rclone_config(source: StorageSource) -> MountConfig:
    """Generate an rclone remote config block for a cloud source."""
    opts = source.options or {}
    backend_type = opts.get("backend", "s3")
    remote_name = source.name.lower().replace(" ", "_")

    # Build the config block — the user fills in secrets via SLOP secrets UI
    if backend_type == "s3":
        provider = opts.get("provider", "AWS")
        conf_block = f"""\
[{remote_name}]
type = s3
provider = {provider}
access_key_id = ${{RCLONE_{remote_name.upper()}_ACCESS_KEY}}
secret_access_key = ${{RCLONE_{remote_name.upper()}_SECRET_KEY}}
region = {opts.get("region", "us-east-1")}
"""
    elif backend_type == "b2":
        conf_block = f"""\
[{remote_name}]
type = b2
account = ${{RCLONE_{remote_name.upper()}_ACCOUNT}}
key = ${{RCLONE_{remote_name.upper()}_KEY}}
"""
    elif backend_type == "sftp":
        conf_block = f"""\
[{remote_name}]
type = sftp
host = {source.remote_host}
user = {opts.get("user", "slop")}
port = {opts.get("port", 22)}
key_file = /config/rclone/{remote_name}_id_rsa
"""
    elif backend_type == "smb":
        conf_block = f"""\
[{remote_name}]
type = smb
host = {source.remote_host}
user = {opts.get("user", "slop")}
pass = ${{RCLONE_{remote_name.upper()}_PASSWORD}}
domain = {opts.get("domain", "WORKGROUP")}
"""
    elif backend_type == "webdav":
        conf_block = f"""\
[{remote_name}]
type = webdav
url = {opts.get("url", "https://example.com")}
vendor = {opts.get("vendor", "other")}
user = {opts.get("user", "")}
pass = ${{RCLONE_{remote_name.upper()}_PASSWORD}}
"""
    else:
        conf_block = f"""\
[{remote_name}]
type = {backend_type}
# Add your backend-specific configuration here
# See: https://rclone.org/{backend_type}/
"""

    vfs_cache = opts.get("vfs_cache_mode", "full")
    dir_cache = opts.get("dir_cache_time", "10s")
    buffer = opts.get("buffer_size", "64M")

    mount_cmd = (
        f"mount {remote_name}: {source.mount_point} "
        f"--allow-non-empty --allow-other "
        f"--vfs-cache-mode {vfs_cache} "
        f"--dir-cache-time {dir_cache} "
        f"--buffer-size {buffer} "
        f"--uid={opts.get('uid', 1000)} --gid={opts.get('gid', 1000)}"
    )

    install_steps = [
        "# rclone config written to: {config_root}/rclone/rclone.conf",
        "# SLOP deploys a dedicated rclone container for this source.",
        f"# Mount command used inside container: rclone {mount_cmd}",
        "# The rclone container shares /mnt with rshared propagation,",
        f"# so media containers at {source.mount_point} see the cloud files.",
    ]

    return MountConfig(
        source=source,
        rclone_remote_name=remote_name,
        rclone_conf_block=conf_block,
        install_steps=install_steps,
    )


# ---------------------------------------------------------------------------
# State DB CRUD for storage sources
# ---------------------------------------------------------------------------


def add_source(
    name: str,
    source_type: str,
    mount_point: str,
    remote_host: str | None = None,
    remote_path: str | None = None,
    options: dict[str, Any] | None = None,
    credentials_key: str | None = None,
    is_primary: bool = False,
) -> StorageSource:
    with StateDB() as db:
        cur = db._c.execute(
            """
            INSERT INTO storage_sources
                (name, source_type, remote_host, remote_path, mount_point,
                 credentials_key, options, is_primary)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                name,
                source_type,
                remote_host,
                remote_path,
                mount_point,
                credentials_key,
                json.dumps(options or {}),
                1 if is_primary else 0,
            ),
        )
        row_id = cur.lastrowid
    if row_id is None:
        raise RuntimeError(
            "INSERT INTO storage_sources did not populate lastrowid — DB error or driver mismatch."
        )
    return get_source(row_id)


def get_source(source_id: int) -> StorageSource:
    with StateDB() as db:
        row = db._c.execute("SELECT * FROM storage_sources WHERE id=?", (source_id,)).fetchone()
    if not row:
        raise KeyError(f"Storage source {source_id} not found")
    return _row_to_source(row)


def list_sources() -> list[StorageSource]:
    with StateDB() as db:
        rows = db._c.execute(
            "SELECT * FROM storage_sources ORDER BY is_primary DESC, name"
        ).fetchall()
    return [_row_to_source(r) for r in rows]


def update_source_status(source_id: int, status: str, error: str | None = None) -> None:
    with StateDB() as db:
        db._c.execute(
            "UPDATE storage_sources SET status=?, error_message=?, updated_at=unixepoch() WHERE id=?",
            (status, error, source_id),
        )


def remove_source(source_id: int) -> None:
    with StateDB() as db:
        db._c.execute("DELETE FROM storage_sources WHERE id=?", (source_id,))


def _row_to_source(row: Any) -> StorageSource:
    cols = [
        "id",
        "name",
        "source_type",
        "remote_host",
        "remote_path",
        "mount_point",
        "credentials_key",
        "options",
        "is_primary",
        "status",
        "error_message",
        "created_at",
        "updated_at",
    ]
    d = dict(zip(cols, row, strict=False)) if not hasattr(row, "keys") else dict(row)
    return StorageSource(
        id=d.get("id"),
        name=d["name"],
        source_type=d["source_type"],
        remote_host=d.get("remote_host"),
        remote_path=d.get("remote_path"),
        mount_point=d["mount_point"],
        credentials_key=d.get("credentials_key"),
        options=json.loads(d.get("options") or "{}"),
        is_primary=bool(d.get("is_primary", 0)),
        status=d.get("status", "inactive"),
        error_message=d.get("error_message"),
    )


# ---------------------------------------------------------------------------
# Mount config dispatcher
# ---------------------------------------------------------------------------


def generate_mount_config(source: StorageSource) -> MountConfig:
    """Generate the appropriate mount configuration for a storage source."""
    if source.source_type == "nfs":
        return generate_nfs_unit(source)
    elif source.source_type == "smb":
        return generate_smb_unit(source)
    elif source.source_type == "rclone":
        return generate_rclone_config(source)
    elif source.source_type == "local":
        return MountConfig(
            source=source,
            install_steps=[
                "# Local path — no mount needed.",
                f"# Ensure {source.mount_point} exists and is accessible.",
                f"ls -la {source.mount_point}",
            ],
        )
    else:
        raise ValueError(f"Unknown source_type: {source.source_type!r}")


# ---------------------------------------------------------------------------
# Mount verification
# ---------------------------------------------------------------------------


def verify_mount(mount_point: str) -> tuple[bool, str]:
    """Check if a path is mounted and accessible.

    Returns (is_mounted, message).
    """
    path = Path(mount_point)
    if not path.exists():
        return False, f"Mount point {mount_point} does not exist."

    try:
        # Check if it's a mount point (different device from parent)
        parent_stat = os.stat(str(path.parent))
        mount_stat = os.stat(str(path))
        is_mountpoint = mount_stat.st_dev != parent_stat.st_dev
    except OSError as e:
        return False, f"Could not stat {mount_point}: {e}"

    if not is_mountpoint:
        # Could still be a bind mount or local — check if readable
        try:
            list(path.iterdir())
            return True, f"{mount_point} is accessible (local path)."
        except PermissionError:
            return False, f"{mount_point} exists but is not readable."
        except OSError as e:
            return False, f"{mount_point} exists but is not accessible: {e}"

    # It's a mount point — check it's actually readable (not stale)
    try:
        list(path.iterdir())
        return True, f"{mount_point} is mounted and readable."
    except OSError as e:
        return False, f"{mount_point} is mounted but not accessible (stale mount?): {e}"


def primary_media_root() -> str | None:
    """Return the mount_point of the primary storage source, or None."""
    try:
        sources = list_sources()
        primary = next((s for s in sources if s.is_primary and s.status == "active"), None)
        return primary.mount_point if primary else None
    except Exception:
        return None
