"""backend/platform/storage_units.py — mount-unit / rclone config generation (#1302 split).

Extracted from ``storage.py`` (which kept growing past the 500-line ``production_code`` cap during
the CI-dead window, #1271) to separate the two concerns: ``storage.py`` now owns the storage-source
data model + persistence (DB CRUD) + live mount verification, while this module owns the **pure
config generation** — turning a :class:`~backend.platform.storage.StorageSource` into a
:class:`MountConfig` (a systemd ``.mount`` unit for NFS/SMB, or an rclone remote block for cloud).

These functions hold no module state and never touch the DB or the host; they take a
``StorageSource`` and return a ``MountConfig``. ``StorageSource`` is imported only under
``TYPE_CHECKING`` (used purely in annotations — never constructed here), so this module has **no
runtime import of** ``storage`` → no import cycle. ``storage`` imports the generators + ``MountConfig``
back and re-exports them, so every existing caller (``storage.generate_mount_config``,
``storage.generate_nfs_unit``, ``storage._sanitize_path_component``, ``storage.MountConfig`` …) keeps
resolving unchanged — a pure move, no behaviour change.
"""

from __future__ import annotations

import re as _re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from backend.platform.storage import StorageSource


@dataclass
class MountConfig:
    """Generated configuration for a storage source."""

    source: StorageSource
    # Systemd .mount unit (nfs/smb)
    systemd_unit: str | None = None
    systemd_unit_name: str | None = None
    # fstab entry (alternative to systemd)
    fstab_entry: str | None = None
    # rclone remote config (rclone sources)
    rclone_remote_name: str | None = None
    rclone_conf_block: str | None = None
    # Install instructions (plain language)
    install_steps: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Systemd mount unit generator (NFS / SMB)
# ---------------------------------------------------------------------------


def _systemd_unit_name(mount_point: str) -> str:
    """Convert a mount path to a systemd unit name.

    /mnt/nas01 → mnt-nas01.mount
    /mnt/cloud/backblaze → mnt-cloud-backblaze.mount
    """
    stripped = mount_point.lstrip("/")
    escaped = stripped.replace("-", "\\x2d").replace("/", "-")
    return f"{escaped}.mount"


def _sanitize_path_component(value: str, field_name: str) -> str:
    """Sanitize a path/host component used in shell commands or unit files.

    Rejects values containing shell metacharacters to prevent command injection
    in systemd unit files and mount commands.
    """
    # Allow: alphanumeric, dots, hyphens, underscores, forward slashes, colons (for IPv6)
    if _re.search(r"[^a-zA-Z0-9./_:\-]", value):
        raise ValueError(
            f"Invalid characters in {field_name} '{value}'. "
            f"Only alphanumeric, dots, hyphens, underscores, slashes, and colons are allowed."
        )
    return value


def generate_nfs_unit(source: StorageSource) -> MountConfig:
    """Generate a systemd .mount unit for an NFS share."""
    opts = source.options or {}
    nfs_version = opts.get("nfs_version", "4.1")
    extra_opts = opts.get("extra_options", "")
    mount_options = f"nfsvers={nfs_version},_netdev,auto,nofail,x-systemd.automount"
    if extra_opts:
        mount_options += f",{extra_opts}"

    unit_name = _systemd_unit_name(source.mount_point)
    host = _sanitize_path_component(source.remote_host or "", "remote_host")
    path = _sanitize_path_component(source.remote_path or "", "remote_path")
    what = f"{host}:{path}"

    unit_content = f"""\
# Generated by SLOP — do not edit manually
# Storage source: {source.name}
# Regenerate: SLOP → Storage → {source.name} → Regenerate Config

[Unit]
Description=SLOP NFS Mount — {source.name}
Documentation=https://github.com/SLOP-Platform/SLOP
Before=docker.service
After=network-online.target
Wants=network-online.target

[Mount]
What={what}
Where={source.mount_point}
Type=nfs
Options={mount_options}
TimeoutSec=30

[Install]
WantedBy=multi-user.target
"""

    install_steps = [
        "sudo apt-get install -y nfs-common",
        f"sudo mkdir -p {source.mount_point}",
        f"sudo cp /etc/slop/mounts/{unit_name} /etc/systemd/system/",
        "sudo systemctl daemon-reload",
        f"sudo systemctl enable --now {unit_name}",
        f"systemctl status {unit_name}",
    ]

    fstab = f"{what}  {source.mount_point}  nfs  {mount_options}  0 0"

    return MountConfig(
        source=source,
        systemd_unit=unit_content,
        systemd_unit_name=unit_name,
        fstab_entry=fstab,
        install_steps=install_steps,
    )


def generate_smb_unit(source: StorageSource) -> MountConfig:
    """Generate a systemd .mount unit for an SMB/CIFS share."""
    opts = source.options or {}
    smb_version = opts.get("smb_version", "3.0")
    uid = opts.get("uid", 1000)
    gid = opts.get("gid", 1000)
    file_mode = opts.get("file_mode", "0664")
    dir_mode = opts.get("dir_mode", "0775")

    # Credentials file path — credentials stored in /etc/slop/secrets/
    cred_path = f"/etc/slop/secrets/{source.name.replace(' ', '_').lower()}.cred"

    mount_options = (
        f"credentials={cred_path},vers={smb_version},"
        f"uid={uid},gid={gid},file_mode={file_mode},dir_mode={dir_mode},"
        f"_netdev,auto,nofail,x-systemd.automount"
    )
    extra = opts.get("extra_options", "")
    if extra:
        mount_options += f",{extra}"

    unit_name = _systemd_unit_name(source.mount_point)
    host = _sanitize_path_component(source.remote_host or "", "remote_host")
    path = _sanitize_path_component(source.remote_path or "", "remote_path")
    what = f"//{host}/{path}"

    unit_content = f"""\
# Generated by SLOP — do not edit manually
# Storage source: {source.name}

[Unit]
Description=SLOP SMB Mount — {source.name}
Documentation=https://github.com/SLOP-Platform/SLOP
Before=docker.service
After=network-online.target
Wants=network-online.target

[Mount]
What={what}
Where={source.mount_point}
Type=cifs
Options={mount_options}
TimeoutSec=30

[Install]
WantedBy=multi-user.target
"""

    install_steps = [
        "sudo apt-get install -y cifs-utils",
        f"sudo mkdir -p {source.mount_point}",
        "# Create credentials file (never store passwords in fstab or unit files):",
        "sudo mkdir -p /etc/slop/secrets",
        f"sudo bash -c 'echo -e \"username=YOUR_USERNAME\\npassword=YOUR_PASSWORD\\ndomain=WORKGROUP\" > {cred_path}'",
        f"sudo chmod 600 {cred_path}",
        f"sudo cp /etc/slop/mounts/{unit_name} /etc/systemd/system/",
        "sudo systemctl daemon-reload",
        f"sudo systemctl enable --now {unit_name}",
        f"systemctl status {unit_name}",
    ]

    fstab = f"{what}  {source.mount_point}  cifs  {mount_options}  0 0"

    return MountConfig(
        source=source,
        systemd_unit=unit_content,
        systemd_unit_name=unit_name,
        fstab_entry=fstab,
        install_steps=install_steps,
    )


# ---------------------------------------------------------------------------
# rclone remote generator (cloud sources)
# ---------------------------------------------------------------------------


def generate_rclone_config(source: StorageSource) -> MountConfig:
    """Generate an rclone remote config block for a cloud source."""
    opts = source.options or {}
    backend_type = opts.get("backend", "s3")
    remote_name = source.name.lower().replace(" ", "_")

    # Build the config block — the user fills in secrets via SLOP secrets UI
    if backend_type == "s3":
        provider = opts.get("provider", "AWS")
        conf_block = f"""\
[{remote_name}]
type = s3
provider = {provider}
access_key_id = ${{RCLONE_{remote_name.upper()}_ACCESS_KEY}}
secret_access_key = ${{RCLONE_{remote_name.upper()}_SECRET_KEY}}
region = {opts.get("region", "us-east-1")}
"""
    elif backend_type == "b2":
        conf_block = f"""\
[{remote_name}]
type = b2
account = ${{RCLONE_{remote_name.upper()}_ACCOUNT}}
key = ${{RCLONE_{remote_name.upper()}_KEY}}
"""
    elif backend_type == "sftp":
        conf_block = f"""\
[{remote_name}]
type = sftp
host = {source.remote_host}
user = {opts.get("user", "slop")}
port = {opts.get("port", 22)}
key_file = /config/rclone/{remote_name}_id_rsa
"""
    elif backend_type == "smb":
        conf_block = f"""\
[{remote_name}]
type = smb
host = {source.remote_host}
user = {opts.get("user", "slop")}
pass = ${{RCLONE_{remote_name.upper()}_PASSWORD}}
domain = {opts.get("domain", "WORKGROUP")}
"""
    elif backend_type == "webdav":
        conf_block = f"""\
[{remote_name}]
type = webdav
url = {opts.get("url", "https://example.com")}
vendor = {opts.get("vendor", "other")}
user = {opts.get("user", "")}
pass = ${{RCLONE_{remote_name.upper()}_PASSWORD}}
"""
    else:
        conf_block = f"""\
[{remote_name}]
type = {backend_type}
# Add your backend-specific configuration here
# See: https://rclone.org/{backend_type}/
"""

    vfs_cache = opts.get("vfs_cache_mode", "full")
    dir_cache = opts.get("dir_cache_time", "10s")
    buffer = opts.get("buffer_size", "64M")

    mount_cmd = (
        f"mount {remote_name}: {source.mount_point} "
        f"--allow-non-empty --allow-other "
        f"--vfs-cache-mode {vfs_cache} "
        f"--dir-cache-time {dir_cache} "
        f"--buffer-size {buffer} "
        f"--uid={opts.get('uid', 1000)} --gid={opts.get('gid', 1000)}"
    )

    install_steps = [
        "# rclone config written to: {config_root}/rclone/rclone.conf",
        "# SLOP deploys a dedicated rclone container for this source.",
        f"# Mount command used inside container: rclone {mount_cmd}",
        "# The rclone container shares /mnt with rshared propagation,",
        f"# so media containers at {source.mount_point} see the cloud files.",
    ]

    return MountConfig(
        source=source,
        rclone_remote_name=remote_name,
        rclone_conf_block=conf_block,
        install_steps=install_steps,
    )


# ---------------------------------------------------------------------------
# Mount config dispatcher
# ---------------------------------------------------------------------------


def generate_mount_config(source: StorageSource) -> MountConfig:
    """Generate the appropriate mount configuration for a storage source."""
    if source.source_type == "nfs":
        return generate_nfs_unit(source)
    elif source.source_type == "smb":
        return generate_smb_unit(source)
    elif source.source_type == "rclone":
        return generate_rclone_config(source)
    elif source.source_type == "local":
        return MountConfig(
            source=source,
            install_steps=[
                "# Local path — no mount needed.",
                f"# Ensure {source.mount_point} exists and is accessible.",
                f"ls -la {source.mount_point}",
            ],
        )
    else:
        raise ValueError(f"Unknown source_type: {source.source_type!r}")
