"""installer/post_install.py — POST_INSTALL.txt renderer and writer.

Implements ADR 0015 §6: renders the operator handoff document from
installer/templates/POST_INSTALL.txt.template, resolves the hostname via a
three-step fallback, and writes the file atomically with mode 0644 and
slop:slop ownership.

The file's existence is the INV-8 write-coupling signal: if POST_INSTALL.txt
exists, the install completed successfully and its smoke test passed.
"""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path
from collections.abc import Callable

from installer._run import run_required

# INV-8 unfilled-placeholder regex (must match nothing in a rendered template).
_UNFILLED_RE = re.compile(r"<[a-z_]+>")

_TEMPLATE_PATH = Path(__file__).parent / "templates" / "POST_INSTALL.txt.template"
_POST_INSTALL_NAME = "POST_INSTALL.txt"


# ── Hostname resolution ───────────────────────────────────────────────────────


def _resolve_hostname(
    *,
    run: Callable = run_required,
) -> str:
    """Return the best hostname for the operator's browser URL.

    Resolution order per ADR 0015 §6:
      1. First non-loopback IPv4 from ``hostname -I``
      2. ``hostname --fqdn``
      3. Literal ``localhost``
    """
    try:
        result = run(["hostname", "-I"], timeout=5.0)
        if result.returncode == 0:
            for ip in result.stdout.strip().split():
                if ip and not ip.startswith("127.") and ip != "::1":
                    return ip
    except Exception:  # noqa: S110 — best-effort probe; intentionally falls through to the localhost fallback
        pass

    try:
        result = run(["hostname", "--fqdn"], timeout=5.0)
        if result.returncode == 0:
            fqdn = result.stdout.strip()
            if fqdn:
                return fqdn
    except Exception:  # noqa: S110 — best-effort probe; intentionally falls through to the localhost fallback
        pass

    return "localhost"


# ── Template rendering ────────────────────────────────────────────────────────


def render(
    *,
    version: str,
    hostname: str,
    port: int,
    install_dir: str,
    data_dir: str,
    completed_at: str,
    template_text: str | None = None,
) -> str:
    """Render the POST_INSTALL.txt template with substituted values.

    Uses .replace() (not .format()) so the <placeholder> syntax is preserved
    until every token is explicitly substituted (INV-8 compatible).

    Raises ValueError if any <[a-z_]+> tokens remain after substitution,
    which indicates a missing placeholder argument or a template drift.
    """
    if template_text is None:
        template_text = _TEMPLATE_PATH.read_text(encoding="utf-8")

    result = template_text
    result = result.replace("<version>", version)
    result = result.replace("<hostname>", hostname)
    result = result.replace("<port>", str(port))
    result = result.replace("<install_dir>", install_dir)
    result = result.replace("<data_dir>", data_dir)
    result = result.replace("<completed_at>", completed_at)

    unfilled = _UNFILLED_RE.findall(result)
    if unfilled:
        raise ValueError(f"POST_INSTALL.txt template has unfilled placeholders: {unfilled}")

    return result


# ── File write ────────────────────────────────────────────────────────────────


def _default_run_chown(path: str) -> None:
    run_required(["chown", "slop:slop", path], timeout=10.0)


def _default_run_chown_root(path: str) -> None:
    run_required(["chown", "root:root", path], timeout=10.0)


def write_wrapper(
    install_dir: Path,
    *,
    run_chown: Callable[[str], None] = _default_run_chown_root,
) -> None:
    """Write the slop CLI wrapper to <install_dir>/bin/slop.

    Sets PYTHONPATH internally so operators need no env setup. Mode 0755,
    owner root:root — invoked via sudo. Purge removes install_dir entirely
    so the wrapper is cleaned up with the rest of the install tree.
    """
    bin_dir = install_dir / "bin"
    bin_dir.mkdir(mode=0o755, exist_ok=True)
    wrapper_path = bin_dir / "slop"
    venv_python = install_dir / ".venv" / "bin" / "python3"
    content = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by installer. Do not edit directly.\n"
        "export PYTHONPATH=" + str(install_dir) + "\n"
        "exec " + str(venv_python) + ' -m installer.main "$@"\n'
    )
    wrapper_path.write_text(content, encoding="utf-8")
    wrapper_path.chmod(0o755)
    run_chown(str(wrapper_path))


def write(
    content: str,
    install_dir: Path,
    *,
    run_chown: Callable[[str], None] = _default_run_chown,
) -> None:
    """Write POST_INSTALL.txt atomically with mode 0644 + slop ownership.

    Writes to a temp file in install_dir, sets mode, chowns, then renames
    atomically (same filesystem as install_dir). Mode 0644 makes the file
    world-readable — it is operator documentation, not sensitive state.
    """
    dest = install_dir / _POST_INSTALL_NAME
    dir_ = install_dir

    fd, tmp_path = tempfile.mkstemp(dir=dir_, prefix=".post-install.tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.chmod(tmp_path, 0o644)
        run_chown(tmp_path)
        os.replace(tmp_path, dest)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
